export const FOCUS_AREAS = [
  {
    title_tr: 'Eğitim & Teknoloji',
    title_en: 'Education & Technology',
    description_tr: 'Eğitimde teknoloji kullanımını yaygınlaştırmak için çalışmalar yapıyoruz. Öğretmenlere ve öğrencilere yönelik eğitim teknolojileri konusunda farkındalık ve beceri kazandırmayı hedefliyoruz.',
    description_en: 'We work to spread the use of technology in education. We aim to raise awareness and build skills in educational technology for teachers and students.',
    activities_tr: [
      'Eğitimcilere yönelik teknoloji kullanımı eğitimleri',
      'Eğitim kurumlarında teknoloji entegrasyonu danışmanlığı',
      'Eğitim teknolojileri konusunda araştırma ve geliştirme çalışmaları',
      'Eğitim yazılımları ve uygulamaları geliştirme',
      'Uzaktan eğitim ve hibrit öğrenme modelleri tasarımı',
    ],
    activities_en: [
      'Technology-use training programs for educators',
      'Technology integration consulting for educational institutions',
      'Research and development in educational technology',
      'Development of educational software and applications',
      'Design of distance and hybrid learning models',
    ],
  },
  {
    title_tr: 'Oyun & Oyun Temelli Öğrenme',
    title_en: 'Gaming & Game-Based Learning',
    description_tr: 'Oyun temelli öğrenme yaklaşımlarını geliştiriyor ve uyguluyoruz. Oyunların eğitimde etkili bir araç olarak kullanılmasını sağlamak için çalışıyoruz.',
    description_en: 'We develop and implement game-based learning approaches. We work to ensure games are used as an effective tool in education.',
    activities_tr: [
      'Eğitsel oyun tasarımı ve geliştirme',
      'Oyunlaştırma (gamification) uygulamaları',
      'Oyun temelli öğrenme metodolojileri geliştirme',
      'Eğitimcilere yönelik oyun temelli öğrenme eğitimleri',
      'Ciddi oyunlar (serious games) tasarımı ve uygulaması',
    ],
    activities_en: [
      'Educational game design and development',
      'Gamification applications',
      'Development of game-based learning methodologies',
      'Game-based learning training for educators',
      'Design and implementation of serious games',
    ],
  },
  {
    title_tr: 'Dijitalleşme & Dijital Okuryazarlık',
    title_en: 'Digitalization & Digital Literacy',
    description_tr: 'Toplumun her kesiminin dijital becerilerini geliştirmeyi hedefliyoruz. Dijital dönüşüm sürecinde kimsenin geride kalmaması için çalışıyoruz.',
    description_en: 'We aim to improve the digital skills of all segments of society and ensure no one is left behind in the digital transformation process.',
    activities_tr: [
      'Dijital okuryazarlık eğitimleri',
      'Dezavantajlı gruplar için dijital beceri kazandırma programları',
      'Dijital vatandaşlık ve güvenli internet kullanımı eğitimleri',
      'Temel kodlama ve programlama eğitimleri',
      'Dijital araçların etkin kullanımı konusunda rehberlik',
    ],
    activities_en: [
      'Digital literacy training',
      'Digital skills programs for disadvantaged groups',
      'Digital citizenship and safe internet use training',
      'Basic coding and programming education',
      'Guidance on effective use of digital tools',
    ],
  },
  {
    title_tr: 'Medya Okuryazarlığı',
    title_en: 'Media Literacy',
    description_tr: 'Medya içeriklerini doğru anlama, analiz etme ve değerlendirme becerilerini geliştirmeye yönelik çalışmalar yapıyoruz. Eleştirel düşünme ve bilinçli medya tüketimi konularında farkındalık yaratıyoruz.',
    description_en: 'We work to develop skills in correctly understanding, analyzing and evaluating media content, raising awareness of critical thinking and conscious media consumption.',
    activities_tr: [
      'Medya okuryazarlığı eğitimleri',
      'Dezenformasyon ve yanlış bilgi ile mücadele programları',
      'Sosyal medya kullanımı ve etkileri konusunda bilinçlendirme',
      'Çocuklar ve gençler için güvenli medya kullanımı rehberleri',
      'Medya içerik üretimi ve etik ilkeler eğitimleri',
    ],
    activities_en: [
      'Media literacy training',
      'Programs to combat disinformation and misinformation',
      'Awareness of social media use and its effects',
      'Safe media-use guides for children and youth',
      'Media content production and ethics training',
    ],
  },
  {
    title_tr: 'Çevre & Sürdürülebilirlik',
    title_en: 'Environment & Sustainability',
    description_tr: 'Çevre bilinci ve sürdürülebilirlik konularında farkındalık yaratmak için teknoloji ve oyun temelli yaklaşımları kullanıyoruz. Sürdürülebilir kalkınma hedeflerine katkıda bulunmayı amaçlıyoruz.',
    description_en: 'We use technology and game-based approaches to raise awareness of environmental consciousness and sustainability, aiming to contribute to sustainable development goals.',
    activities_tr: [
      'Çevre eğitimi için dijital araçlar ve oyunlar geliştirme',
      'Sürdürülebilirlik konusunda farkındalık kampanyaları',
      'Ekolojik ayak izi hesaplama ve azaltma programları',
      'Geri dönüşüm ve atık yönetimi eğitimleri',
      'Yenilenebilir enerji ve iklim değişikliği konularında bilinçlendirme',
    ],
    activities_en: [
      'Digital tools and games for environmental education',
      'Sustainability awareness campaigns',
      'Ecological footprint calculation and reduction programs',
      'Recycling and waste management training',
      'Awareness on renewable energy and climate change',
    ],
  },
  {
    title_tr: 'Gençlik & Gönüllülük',
    title_en: 'Youth & Volunteering',
    description_tr: 'Gençlerin ve gönüllülerin katılımıyla projeler geliştiriyoruz. Gençlerin potansiyellerini gerçekleştirmelerine ve toplumsal sorunlara çözüm üretmelerine destek oluyoruz.',
    description_en: 'We develop projects with the participation of young people and volunteers, supporting them in realizing their potential and solving social problems.',
    activities_tr: [
      'Gençlik projeleri ve girişimleri destekleme',
      'Gönüllülük programları ve eğitimleri',
      'Gençlik liderliği ve katılımı programları',
      'Ulusal ve uluslararası gençlik değişimleri',
      'Gençlik politikaları geliştirme ve savunuculuk',
    ],
    activities_en: [
      'Supporting youth projects and initiatives',
      'Volunteering programs and training',
      'Youth leadership and participation programs',
      'National and international youth exchanges',
      'Youth policy development and advocacy',
    ],
  },
  {
    title_tr: 'İnsan Hakları & Eşitlik',
    title_en: 'Human Rights & Equality',
    description_tr: 'İnsan hakları ve eşitlik konularında farkındalık yaratmak için teknoloji ve oyun temelli yaklaşımları kullanıyoruz. Herkes için eşit fırsatlar yaratmayı hedefliyoruz.',
    description_en: 'We use technology and game-based approaches to raise awareness of human rights and equality, aiming to create equal opportunities for everyone.',
    activities_tr: [
      'İnsan hakları eğitimleri ve farkındalık kampanyaları',
      'Ayrımcılıkla mücadele programları',
      'Toplumsal cinsiyet eşitliği projeleri',
      'Kapsayıcı eğitim modelleri geliştirme',
      'Dezavantajlı grupların güçlendirilmesi çalışmaları',
    ],
    activities_en: [
      'Human rights training and awareness campaigns',
      'Anti-discrimination programs',
      'Gender equality projects',
      'Development of inclusive education models',
      'Empowerment work for disadvantaged groups',
    ],
  },
  {
    title_tr: 'Sosyal İnovasyon & Girişimcilik',
    title_en: 'Social Innovation & Entrepreneurship',
    description_tr: 'Toplumsal sorunlara yenilikçi çözümler üretmek için sosyal inovasyon ve girişimcilik yaklaşımlarını destekliyoruz. Sürdürülebilir ve ölçeklenebilir çözümler geliştirmeyi amaçlıyoruz.',
    description_en: 'We support social innovation and entrepreneurship approaches to produce innovative solutions to social problems, aiming to develop sustainable and scalable solutions.',
    activities_tr: [
      'Sosyal inovasyon laboratuvarları ve atölyeleri',
      'Sosyal girişimcilik eğitimleri ve mentorluk programları',
      'Sosyal etki ölçümü ve değerlendirmesi',
      'Sosyal girişimleri destekleme ve ölçeklendirme',
      'Sosyal inovasyon yarışmaları ve hackathonlar',
    ],
    activities_en: [
      'Social innovation labs and workshops',
      'Social entrepreneurship training and mentorship programs',
      'Social impact measurement and evaluation',
      'Supporting and scaling social enterprises',
      'Social innovation competitions and hackathons',
    ],
  },
]
